// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbPendingTx

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type PendingTransaction struct {
	ID              uuid.UUID
	TxID            string
	Address         string
	ReceiverAddress string
	Status          string
	Amount          string
	Fee             string
	Priority        sql.NullInt32
	Message         sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type PendingTxDatum struct {
	PendingID  uuid.UUID
	TxRef      uuid.UUID
	RawTx      json.RawMessage
	PubKeyHash string
}
