// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbchain

import (
	"database/sql"

	"github.com/google/uuid"
)

type Block struct {
	ID         uuid.UUID
	BID        string
	PrevHash   sql.NullString
	Nonce      int64
	Height     int64
	MerkleRoot string
	Nbits      int64
	TxCount    int64
	NchainWork string
	Size       float64
	Timestamp  int64
}

type Transaction struct {
	ID       uuid.UUID
	TxID     string
	BID      string
	CreateAt int64
	Amount   sql.NullString
	Fee      sql.NullString
	Fromhash sql.NullString
	Tohash   sql.NullString
}

type TxInput struct {
	ID        uuid.UUID
	TxID      string
	InputTxID sql.NullString
	OutIndex  int64
	Sig       sql.NullString
	BID       string
	PubKey    sql.NullString
}

type TxOutput struct {
	ID         uuid.UUID
	TxID       string
	Index      int64
	Value      string
	BID        string
	PubKeyHash string
}
