// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbchain

import (
	"database/sql"

	"github.com/google/uuid"
)

type Block struct {
	ID         uuid.UUID
	BID        string
	PrevHash   sql.NullString
	Nonce      int64
	Height     int64
	MerkleRoot string
	Difficulty int64
	TxCount    int64
	NchainWork string
	Timestamp  int64
}

type Transaction struct {
	ID       uuid.UUID
	TxID     string
	BID      string
	CreateAt sql.NullTime
}

type TxInput struct {
	ID        uuid.UUID
	TxID      string
	InputTxID string
	OutIndex  int64
	Sig       string
	PubKey    string
}

type TxOutput struct {
	ID         uuid.UUID
	TxID       string
	Index      int64
	Value      string
	PubKeyHash string
}
