import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import UIProvider from '@/components/providers/ui-provider';
import ReactQueryProvider from '@/components/providers/react-query-provider';
import ModalProvider from '@/components/providers/modal-provider';
import { WalletProvider } from '@/components/providers/wallet-provider';
import { ThemeProvider } from '@/components/providers/theme-provider';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} font-sans mdl-js`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <WalletProvider>
              <UIProvider>
                <ModalProvider />
                {children}
              </UIProvider>
            </WalletProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
