import type { Metadata } from 'next';
import '@/styles/globals.css';
import { Geist, Geist_Mono } from 'next/font/google';
import UIProvider from '@/components/providers/ui-provider';
import ReactQueryProvider from '@/components/providers/react-query-provider';
import ModalProvider from '@/components/providers/modal-provider';
import { WalletProvider } from '@/components/providers/wallet-provider';
import { ThemeProvider } from '@/components/providers/theme-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="mdl-js" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <WalletProvider>
              <UIProvider>
                <ModalProvider>{children}</ModalProvider>
              </UIProvider>
            </WalletProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
