// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbwallet

import (
	"database/sql"

	"github.com/google/uuid"
)

type Wallet struct {
	ID            uuid.UUID
	Address       string
	PublicKey     string
	PublicKeyHash string
	Balance       string
	CreateAt      sql.NullTime
	LastLogin     sql.NullTime
}

type WalletAccessLog struct {
	ID         uuid.UUID
	WalletID   uuid.NullUUID
	AccessTime sql.NullTime
	Ip         sql.NullString
	UserAgent  sql.NullString
	AccessType sql.NullString
}
