// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbPeer

import (
	"github.com/google/uuid"
)

type Peer struct {
	ID         uuid.UUID
	Peerid     string
	Multiaddrs string
	Pubkey     string
	Timestamp  int64
	Signature  string
	Status     int32
}
