// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package dbPeer

import (
	"context"
)

const findPeers = `-- name: FindPeers :many
SELECT id, peerid, multiaddrs, pubkey, timestamp, signature, status FROM peers
`

func (q *Queries) FindPeers(ctx context.Context) ([]Peer, error) {
	rows, err := q.db.QueryContext(ctx, findPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Peer
	for rows.Next() {
		var i Peer
		if err := rows.Scan(
			&i.ID,
			&i.Peerid,
			&i.Multiaddrs,
			&i.Pubkey,
			&i.Timestamp,
			&i.Signature,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
