// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbutxo

import (
	"github.com/google/uuid"
)

type Utxo struct {
	ID          uuid.UUID
	TxID        string
	OutputIndex int64
	Value       string
	PubKeyHash  string
	BlockID     string
}
